# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MDY5Y2Y2ODk0NmI5NzczOTZkZmE0NTExYTc0YjZiYjIzMDEwOWYyOTkzNWUzOGMzZWEzNjhjZGQzNmZlYjYxNWNkMDBiZmUzYWYyZGEyYWRkMzI0NDJiMmJjMGM0OTc3N2U3ZWFhMzU3ZmI1YTlhMzY5NGQxZGZiN2IwN2EyNjU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
